package view.pokedex;

import controller.SpecieController;
import view.pokedex.components.TypeComboBoxModel;
import view.pokedex.components.SecondaryTypeComboBoxModel;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Arrays;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.MoveModel;
import model.TypeModel;
import model.entities.Specie;
import model.entities.Sprite;
import model.entities.Type;
import utilities.string.StringComparator;
import utilities.sound.SoundPlayer;
import utilities.sound.Sound;
import view.MainFrame;
import view.pokedex.components.MovementTableModel;
import view.pokedex.components.SpriteJLabel;

/**
 *
 * @author Adrian Vazquez
 */
public class CreateSpecieView extends PokedexView {

    /**
     * Creates new form CreateSpecie
     */
    // OTHER MODELS
    private TypeModel typeModel;
    private TypeComboBoxModel typeComboBoxModel;
    private SecondaryTypeComboBoxModel secondaryTypeComboBoxModel;

    private Sound loadedCry = null;

    private JFrame frame;

    public CreateSpecieView(TypeModel typeModel, SpecieController specieController, JFrame frame) {

        super(specieController.getModel(), specieController);

        this.frame = frame;

        this.typeModel = typeModel;

        this.typeComboBoxModel = new TypeComboBoxModel(typeModel);
        this.secondaryTypeComboBoxModel = new SecondaryTypeComboBoxModel(typeModel);

        initComponents();

        setup();

        refresh();

    }

    private void setup() {

        try {
            // SETUP EXAMPLE SPRITE
            ((SpriteJLabel) (this.jLabelBackImageSprite)).setup(generateDefaultSprite("Resources\\BattleHUD\\Pokedex\\MISSINGNO\\Sprite\\BACK"));
            ((SpriteJLabel) (this.jLabelFrontImageSprite)).setup(generateDefaultSprite("Resources\\BattleHUD\\Pokedex\\MISSINGNO\\Sprite\\FRONT"));

            // SETUP EXAMPLE CRY
            this.loadedCry = new Sound(new File("Resources\\BattleHUD\\Pokedex\\MISSINGNO\\Sound\\151-Mew.wav"));

            // SETUP TYPE COMBO BOXES
            this.jComboBoxType.getModel().setSelectedItem(this.typeModel.getEntity("Psychic").getName()); // EXAMPLE VALUE.
            this.secondaryTypeComboBoxModel.setSelectedItem("None");

            ItemListener listener = new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {

                    if (jComboBoxType.getModel().getSelectedItem().equals(jComboBoxSecondaryType.getModel().getSelectedItem())) {
                        jComboBoxSecondaryType.getModel().setSelectedItem("None");
                        refresh();
                    }
                }
            };

            this.jComboBoxType.addItemListener(listener);
            this.jComboBoxSecondaryType.addItemListener(listener);

        } catch (Exception ex) {
            Logger.getLogger(CreateSpecieView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private Sprite generateDefaultSprite(String pathname) throws Exception {

        File f = new File(pathname);

        File[] files = f.listFiles();

        List<BufferedImage> animation = new LinkedList<>();

        Arrays.sort(files, new Comparator<File>() {
            @Override
            public int compare(File o1, File o2) {

                return new StringComparator().compare(o1.getName(), o2.getName());
            }
        });

        for (File file : files) {

            if (file.isFile()) {

                try {
                    animation.add(ImageIO.read(file));
                } catch (Exception e) {
                }

            }

        }

        BufferedImage imgs[] = new BufferedImage[animation.size()];

        for (int i = 0; i < animation.size(); i++) {

            imgs[i] = utilities.image.ImageUtil.resize(animation.get(i), 300, 300);

        }

        return new Sprite(imgs, this.jSliderRefreshRate.getModel().getMaximum() - ((int) Long.parseLong(this.jLabelSpriteSpeed.getText())) + 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFrontImageSprite = new SpriteJLabel();
        jLabelBackImageSprite = new SpriteJLabel();
        jButtonLoadFrontSidePokemon = new javax.swing.JButton();
        jButtonLoadBackSidePokemon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPokedexId = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jTextFieldHeight = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldWeight = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMinHp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMinAttack = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMaxAttack = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldMinSpecialAttack = new javax.swing.JTextField();
        jTextFieldMinDefense = new javax.swing.JTextField();
        jTextFieldMinSpecialDefense = new javax.swing.JTextField();
        jTextFieldMaxHp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldMaxSpecialAttack = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMaxDefense = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldMaxSpecialDefense = new javax.swing.JTextField();
        jTextFieldMinSpeed = new javax.swing.JTextField();
        jTextFieldMaxSpeed = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSpinnerPrecision = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jSpinnerEvasion = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxSecondaryType = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButtonPlayCry = new javax.swing.JButton();
        jButtonLoadCryAudio = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabelSpriteSpeed = new javax.swing.JLabel();
        jSliderRefreshRate = new javax.swing.JSlider();
        jLabel27 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonCreateSpecie = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        movementTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1350, 800));

        jLabelFrontImageSprite.setText("frontImageSprite");
        jLabelFrontImageSprite.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabelBackImageSprite.setText("backImageSprite");
        jLabelBackImageSprite.setPreferredSize(new java.awt.Dimension(200, 200));

        jButtonLoadFrontSidePokemon.setText("Load front side images");
        jButtonLoadFrontSidePokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadFrontSidePokemonActionPerformed(evt);
            }
        });

        jButtonLoadBackSidePokemon.setText("Load back side images");
        jButtonLoadBackSidePokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadBackSidePokemonActionPerformed(evt);
            }
        });

        jLabel1.setText("Pokédex ID: ");

        jLabel2.setText("Name:");

        jTextFieldPokedexId.setText("151");

        jTextFieldName.setText("Mew");
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel.setText("Height: ");

        jTextFieldHeight.setText("0.4");

        jLabel4.setText("Weight: ");

        jTextFieldWeight.setText("4.0");

        jLabel5.setText("Min. HP :");

        jTextFieldMinHp.setText("310");

        jLabel6.setText("Min. attack:");

        jTextFieldMinAttack.setText("184");

        jLabel7.setText("Max. HP: ");

        jTextFieldMaxAttack.setText("328");

        jLabel8.setText("Max. attack: ");

        jLabel9.setText("Min. special attack:");

        jTextFieldMinSpecialAttack.setText("184");

        jTextFieldMinDefense.setText("184");

        jTextFieldMinSpecialDefense.setText("184");

        jTextFieldMaxHp.setText("404");

        jLabel10.setText("Max. special attack");

        jTextFieldMaxSpecialAttack.setText("328");

        jLabel11.setText("Max. defense");

        jLabel12.setText("Min. defense: ");

        jTextFieldMaxDefense.setText("328");

        jLabel13.setText("Min. special defense:  ");

        jLabel14.setText("Max. special defense: ");

        jTextFieldMaxSpecialDefense.setText("328");

        jTextFieldMinSpeed.setText("184");

        jTextFieldMaxSpeed.setText("328");

        jLabel15.setText("Min. speed: ");

        jLabel16.setText("Max. speed: ");

        jLabel17.setText("Precision: ");

        jSpinnerPrecision.setModel(new javax.swing.SpinnerNumberModel(100, 30, 100, 5));

        jLabel18.setText("Evasion: ");

        jSpinnerEvasion.setModel(new javax.swing.SpinnerNumberModel(100, 0, 600, 1));

        jLabel19.setText("%  (30 - 100)");

        jLabel20.setText("%  (0 - 600)");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jTextAreaDescription.setText("Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people.");
        jTextAreaDescription.setWrapStyleWord(true);
        jTextAreaDescription.setLineWrap(true);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jLabel21.setText("Pokédex description: ");

        jLabel22.setText("Type:");

        jComboBoxType.setModel(this.typeComboBoxModel);

        jLabel23.setText("Secondary type: ");

        jComboBoxSecondaryType.setModel(this.secondaryTypeComboBoxModel);

        jLabel24.setText("m");

        jLabel25.setText("kg");

        jButtonPlayCry.setText("Play cry");
        jButtonPlayCry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayCryActionPerformed(evt);
            }
        });

        jButtonLoadCryAudio.setText("Load cry audio");
        jButtonLoadCryAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadCryAudioActionPerformed(evt);
            }
        });

        jLabel26.setText("Cry:");

        jLabelSpriteSpeed.setText("30");

        jSliderRefreshRate.getModel().setMaximum(100);
        jSliderRefreshRate.getModel().setMinimum(1);
        jSliderRefreshRate.getModel().setValue(((int)Long.parseLong(this.jLabelSpriteSpeed.getText())));
        jSliderRefreshRate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRefreshRateStateChanged(evt);
            }
        });

        jLabel27.setText("Sprite speed: ");

        jButton4.setText("Preview");

        jLabel3.setText("Attacks it can learn:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13))
                                .addComponent(jLabel6))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinnerPrecision)
                                            .addComponent(jSpinnerEvasion))
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldMinSpecialAttack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldMinAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldMinHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel16)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldHeight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                            .addComponent(jTextFieldWeight, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextFieldPokedexId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldMinSpecialDefense, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldMinDefense, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldMinSpeed)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaxHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaxAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaxSpecialAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaxDefense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaxSpecialDefense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jButtonPlayCry, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jButtonLoadCryAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxSecondaryType, 0, 123, Short.MAX_VALUE)
                                            .addComponent(jComboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSpriteSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSliderRefreshRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jTextFieldPokedexId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel)
                            .addComponent(jTextFieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMinHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaxHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBoxSecondaryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMinAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldMaxAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonLoadCryAudio)
                        .addComponent(jButtonPlayCry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMinSpecialAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jTextFieldMaxSpecialAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMinDefense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldMaxDefense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMinSpecialDefense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jLabelSpriteSpeed))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldMaxSpecialDefense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMinSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(jTextFieldMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderRefreshRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jSpinnerPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jButton4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSpinnerEvasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jButtonCreateSpecie.setText("Create specie");
        jButtonCreateSpecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateSpecieActionPerformed(evt);
            }
        });

        movementTable.setModel(new MovementTableModel(new MoveModel()));
        jScrollPane2.setViewportView(movementTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFrontImageSprite, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jLabelBackImageSprite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLoadBackSidePokemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLoadFrontSidePokemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCreateSpecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelFrontImageSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLoadFrontSidePokemon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBackImageSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLoadBackSidePokemon))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCreateSpecie)
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadSprite(SpriteJLabel spriteLabel) {
        String desktopDir = System.getProperty("user.home") + "/Desktop";

        JFileChooser fileChooser = new JFileChooser(desktopDir);

        fileChooser.setMultiSelectionEnabled(true);

        fileChooser.setFileFilter(new FileNameExtensionFilter("Portable Network Graphics (.PNG)", "PNG"));

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            File[] files = fileChooser.getSelectedFiles();

            Arrays.sort(files, new Comparator<File>() {
                @Override
                public int compare(File o1, File o2) {

                    return new StringComparator().compare(o1.getName(), o2.getName());
                }
            });

            if (files.length > 1) {

                BufferedImage[] imgs = new BufferedImage[files.length];
                try {
                    for (int i = 0; i < files.length; i++) {

                        imgs[i] = ImageIO.read(files[i]);
                        imgs[i] = utilities.image.ImageUtil.resize(imgs[i], 300, 300);
                    }

                    Sprite sprite = new Sprite(imgs, this.jSliderRefreshRate.getModel().getMaximum() - ((int) Long.parseLong(this.jLabelSpriteSpeed.getText())) + 1);

                    spriteLabel.setup(sprite);

                } catch (Exception ex) {
                    utilities.DisplayMessage.showErrorDialog(ex.getLocalizedMessage());
                }

            } else {
                utilities.DisplayMessage.showErrorDialog("ERROR: SELECT AT LEAST 2 IMAGES (CTRL + CLICK)");
            }

        }
    }

    private void jButtonLoadFrontSidePokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadFrontSidePokemonActionPerformed

        loadSprite((SpriteJLabel) this.jLabelFrontImageSprite);

    }//GEN-LAST:event_jButtonLoadFrontSidePokemonActionPerformed

    private void jButtonLoadBackSidePokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadBackSidePokemonActionPerformed
        loadSprite((SpriteJLabel) this.jLabelBackImageSprite);
    }//GEN-LAST:event_jButtonLoadBackSidePokemonActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jSliderRefreshRateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRefreshRateStateChanged

        Sprite back = ((SpriteJLabel) (this.jLabelBackImageSprite)).getSprite();
        Sprite front = ((SpriteJLabel) (this.jLabelFrontImageSprite)).getSprite();

        try {

            back.setRefreshRate(this.jSliderRefreshRate.getModel().getMaximum() - this.jSliderRefreshRate.getModel().getValue() + 1);
            front.setRefreshRate(this.jSliderRefreshRate.getModel().getMaximum() - this.jSliderRefreshRate.getModel().getValue() + 1);

            this.jLabelSpriteSpeed.setText((this.jSliderRefreshRate.getModel().getValue()) + "");
        } catch (Exception ex) {
            Logger.getLogger(CreateSpecieView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jSliderRefreshRateStateChanged

    private void jButtonCreateSpecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateSpecieActionPerformed

        String name = jTextFieldName.getText();

        Type type = null;
        Type secondaryType = null;

        List<Type> listOfTypes = this.typeModel.getAll();

        for (int i = 0; ((i < listOfTypes.size()) && (type == null || secondaryType == null)); i++) {

            if (listOfTypes.get(i).getName().equalsIgnoreCase(((String) this.jComboBoxType.getModel().getSelectedItem()))) {
                type = listOfTypes.get(i);
            } else if (listOfTypes.get(i).getName().equalsIgnoreCase(((String) this.jComboBoxSecondaryType.getModel().getSelectedItem()))) {
                secondaryType = listOfTypes.get(i);
            }

        }

        Sprite front = ((SpriteJLabel) this.jLabelFrontImageSprite).getSprite();
        Sprite back = ((SpriteJLabel) this.jLabelBackImageSprite).getSprite();
        Float height = (float) Double.parseDouble(this.jTextFieldHeight.getText());
        Float weight = (float) Double.parseDouble(this.jTextFieldWeight.getText());
        Integer pokedexID = (int) Long.parseLong(jTextFieldPokedexId.getText());
        Integer maxHP = (int) Long.parseLong(jTextFieldMaxHp.getText());
        Integer minHP = (int) Long.parseLong(jTextFieldMinHp.getText());
        Integer maxAttack = (int) Long.parseLong(jTextFieldMaxAttack.getText());
        Integer minAttack = (int) Long.parseLong(jTextFieldMinAttack.getText());
        Integer maxSpecialAttack = (int) Long.parseLong(jTextFieldMaxSpecialAttack.getText());
        Integer minSpecialAttack = (int) Long.parseLong(jTextFieldMinSpecialAttack.getText());
        Integer maxDefense = (int) Long.parseLong(jTextFieldMaxDefense.getText());
        Integer minDefense = (int) Long.parseLong(jTextFieldMinDefense.getText());
        Integer maxSpecialDefense = (int) Long.parseLong(jTextFieldMaxSpecialDefense.getText());
        Integer minSpecialDefense = (int) Long.parseLong(jTextFieldMinSpecialDefense.getText());
        Integer maxSpeed = (int) Long.parseLong(jTextFieldMaxSpeed.getText());
        Integer minSpeed = (int) Long.parseLong(jTextFieldMinSpeed.getText());
        Float precision = ((new Float("" + jSpinnerPrecision.getModel().getValue())) / 100);
        Float evasion = (new Float("" + jSpinnerEvasion.getModel().getValue())) / 100;
        String description = jTextAreaDescription.getText();
        Sound cry = loadedCry;

        List<Object> data = new LinkedList<>();

        data.add(name);
        data.add(type);
        data.add(secondaryType);
        data.add(front);
        data.add(back);
        data.add(height);
        data.add(weight);
        data.add(pokedexID);
        data.add(maxHP);
        data.add(minHP);
        data.add(maxAttack);
        data.add(minAttack);
        data.add(maxSpecialAttack);
        data.add(minSpecialAttack);
        data.add(maxDefense);
        data.add(minDefense);
        data.add(maxSpecialDefense);
        data.add(minSpecialDefense);
        data.add(maxSpeed);
        data.add(minSpeed);
        data.add(precision);
        data.add(evasion);
        data.add(description);
        data.add(cry);

        Specie specie = this.getController().createEntity(data);

        boolean exist = false;
        int i = 0;

        List<Specie> specieList = this.getModel().getAll();

        if (specieList.size() >= 999) {
            utilities.DisplayMessage.showErrorDialog("There are " + specieList.size() + " pokémon, remove some species to add others.");
        } else {

            while (i < specieList.size() && !exist) {

                if (specieList.get(i).getName().equals(specie.getName()) || specieList.get(i).getPokedexID().equals(specie.getPokedexID())) {
                    exist = true;
                }
                i++;
            }

            if (!exist) {

                specie.setMovementsCanLearn(((MovementTableModel) this.movementTable.getModel()).getSelectedMoves());

                this.getController().newEntityGesture(specie);

            } else {
                utilities.DisplayMessage.showErrorDialog("This specie is already created.");
            }
        }

        this.frame.dispose();
        MainFrame.getInstance().previousView();
        MainFrame.getInstance().previousView();

    }//GEN-LAST:event_jButtonCreateSpecieActionPerformed

    private void jButtonPlayCryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayCryActionPerformed

        if (loadedCry != null) {
            SoundPlayer.getInstance().playEffectChannel(loadedCry);
        }
    }//GEN-LAST:event_jButtonPlayCryActionPerformed

    private void jButtonLoadCryAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadCryAudioActionPerformed

        String desktopDir = System.getProperty("user.home") + "/Desktop";

        JFileChooser fileChooser = new JFileChooser(desktopDir);

        fileChooser.setFileFilter(new FileNameExtensionFilter("WAV Audio File (.WAV)", "wav"));

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            File audiofile = fileChooser.getSelectedFile();

            try {
                Sound cry = new Sound(audiofile);

                if (cry.getClip().getMicrosecondLength() <= 1e+7) { // The maximum cry length must be 10 seconds or less
                    this.loadedCry = cry;
                } else {
                    utilities.DisplayMessage.showErrorDialog("The maximum cry length must be 10 seconds or less");
                }

            } catch (Exception ex) {
                Logger.getLogger(CreateSpecieView.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonLoadCryAudioActionPerformed

    @Override
    public void refresh() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCreateSpecie;
    private javax.swing.JButton jButtonLoadBackSidePokemon;
    private javax.swing.JButton jButtonLoadCryAudio;
    private javax.swing.JButton jButtonLoadFrontSidePokemon;
    private javax.swing.JButton jButtonPlayCry;
    private javax.swing.JComboBox<String> jComboBoxSecondaryType;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackImageSprite;
    private javax.swing.JLabel jLabelFrontImageSprite;
    private javax.swing.JLabel jLabelSpriteSpeed;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderRefreshRate;
    private javax.swing.JSpinner jSpinnerEvasion;
    private javax.swing.JSpinner jSpinnerPrecision;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldHeight;
    private javax.swing.JTextField jTextFieldMaxAttack;
    private javax.swing.JTextField jTextFieldMaxDefense;
    private javax.swing.JTextField jTextFieldMaxHp;
    private javax.swing.JTextField jTextFieldMaxSpecialAttack;
    private javax.swing.JTextField jTextFieldMaxSpecialDefense;
    private javax.swing.JTextField jTextFieldMaxSpeed;
    private javax.swing.JTextField jTextFieldMinAttack;
    private javax.swing.JTextField jTextFieldMinDefense;
    private javax.swing.JTextField jTextFieldMinHp;
    private javax.swing.JTextField jTextFieldMinSpecialAttack;
    private javax.swing.JTextField jTextFieldMinSpecialDefense;
    private javax.swing.JTextField jTextFieldMinSpeed;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPokedexId;
    private javax.swing.JTextField jTextFieldWeight;
    private javax.swing.JTable movementTable;
    // End of variables declaration//GEN-END:variables
}
