/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.pokedex;

import controller.SpecieController;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import model.TypeModel;

/**
 *
 * @author Adrian Vazquez
 */
public class PokedexViewImpl extends PokedexView{

    public PokedexViewImpl(SpecieController specieController, TypeModel typeModel) {
        super(specieController.getModel(), specieController);
        initComponents();
        
        int w, h;
        
        w = (int) (this.pokedexEntryPanel.getSize().getWidth()*0.35);
        h = (int) this.pokedexEntryPanel.getSize().getHeight();
        
        this.jSplitPane1.remove(this.pokedexSpecieListPane);
        
        this.pokedexSpecieListPane = new JScrollPane(new PokedexSpecieListView(getModel().getAll(), new Dimension(w, h), (PokedexEntryView) pokedexEntryPanel, specieController, typeModel));
        this.pokedexSpecieListPane.getVerticalScrollBar().setUnitIncrement(6);
        
        this.jSplitPane1.add(this.pokedexSpecieListPane);
        
        repaint();
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pokedexEntryPanel = new PokedexEntryView();
        pokedexSpecieListPane = new javax.swing.JScrollPane();

        jSplitPane1.setDividerLocation(700);

        int w = (int) (pokedexEntryPanel.getSize().width * (1.35));
        int h = (int) pokedexEntryPanel.getSize().height;

        Dimension preferredSize = new Dimension( w, h);

        jSplitPane1.setPreferredSize(preferredSize);

        this.setPreferredSize(preferredSize);
        int location = (int) pokedexEntryPanel.getSize().getWidth();
        jSplitPane1.setDividerLocation(location);
        jSplitPane1.setEnabled(false);

        javax.swing.GroupLayout pokedexEntryPanelLayout = new javax.swing.GroupLayout(pokedexEntryPanel);
        pokedexEntryPanel.setLayout(pokedexEntryPanelLayout);
        pokedexEntryPanelLayout.setHorizontalGroup(
            pokedexEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        pokedexEntryPanelLayout.setVerticalGroup(
            pokedexEntryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(pokedexEntryPanel);
        jSplitPane1.setRightComponent(pokedexSpecieListPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void refresh() {
        repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLayeredPane pokedexEntryPanel;
    private javax.swing.JScrollPane pokedexSpecieListPane;
    // End of variables declaration//GEN-END:variables
}
